name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  publish_to_github_packages:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      
    - name: Push prod image to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: perdanadev/ruby-docker-images/prod
        dockerfile: Prod.dockerfile
        tags: latest, 2.6.5
      
    - name: Push dev image to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: perdanadev/ruby-docker-images/dev
        dockerfile: Dev.dockerfile
        tags: latest, 2.6.5
        
  publish_to_docker_hub:
    
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
        
    - name: Push prod image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: perdanadev/ruby
        dockerfile: Prod.dockerfile
        tags: latest, 2.6.5
      
    - name: Push dev image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: perdanadev/ruby
        dockerfile: Dev.dockerfile
        tags: latest-dev, 2.6.5-dev
